### ISSUE TITLE
None of it works?? Platformio or Arduino

### ISSUE THREAD

**Issue by Diddle1** [Vretu-Dev/ESP32-Captive-Portal-Google#5]

**Comment by Vretu-Dev** [comment]
Can you explain what exactly is not working?

**Comment by Diddle1** [comment]
> Can you explain what exactly is not working?

I can't seem to get the google and roboto files to work in arduino ide, and for platformio when i press the arrow to flash it. It flashes and shows everything its adding but nothing works not even an ap?

**Comment by Vretu-Dev** [comment]
Project is 

> > Can you explain what exactly is not working?
> 
> I can't seem to get the google and roboto files to work in arduino ide, and for platformio when i press the arrow to flash it. It flashes and shows everything its adding but nothing works not even an ap?

You don't need to flash every font, just go to main.cpp and click the arrow,

**Comment by Diddle1** [comment]
I got it to work through platformIO my apologies!! Thanks!!

**Comment by Vretu-Dev** [comment]
Okay, If you encounter any problems do not hesitate to report them ;)

**Comment by Diddle1** [comment]
> Okay, If you encounter any problems do not hesitate to report them ;)

This is exactly what i was looking for its perfect! Last question if you dont mind i havent used visual code but if were to change the ssid would i do that in the main.cpp before i click the arrow?

**Comment by Vretu-Dev** [comment]
> > Okay, If you encounter any problems do not hesitate to report them ;)
> 
> This is exactly what i was looking for its perfect! Last question if you dont mind i havent used visual code but if were to change the ssid would i do that in the main.cpp before i click the arrow?

Yes you can change the ssid in main.cpp but it will cause that when you use the "Reset EEPROM" button in the "http://4.3.2.1/manage" panel, ESP will take this value, by default "captive". On the other hand, if you change the SSID in the panel it will be stored in the eeprom memory so you don't have to set it again after reboot

**Comment by Vretu-Dev** [comment]
The function responsible for changing SSIDs is not well tested, and it may happen, for example, that a device does not want to connect to ESP when there is a "-" or space symbol in the SSID name. In this case, the only option is to clear the ESP memory and reinstall it.
